import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "inverse-primary": "#a5d0b9",
        "tertiary": "#27261a",
        "primary-fixed": "#c1ecd4",
        "on-error": "#ffffff",
        "on-background": "#191d0e",
        "on-tertiary-container": "#a8a695",
        "secondary": "#7e5700",
        "on-surface-variant": "#414844",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dcc4",
        "secondary-fixed-dim": "#f9bc52",
        "surface-container-highest": "#e0e5cc",
        "secondary-container": "#ffc157",
        "on-secondary": "#ffffff",
        "background": "#f7fce3",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#3f6653",
        "tertiary-fixed": "#e6e3d0",
        "surface-bright": "#f7fce3",
        "on-primary-container": "#86af99",
        "on-secondary-fixed": "#281900",
        "on-surface": "#191d0e",
        "surface": "#f7fce3",
        "on-secondary-container": "#744f00",
        "tertiary-fixed-dim": "#c9c7b5",
        "primary-container": "#1b4332",
        "primary-fixed-dim": "#a5d0b9",
        "surface-container": "#ecf0d8",
        "surface-container-low": "#f2f6dd",
        "on-secondary-fixed-variant": "#604100",
        "outline-variant": "#c1c8c2",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002114",
        "outline": "#717973",
        "tertiary-container": "#3d3c2f",
        "surface-container-high": "#e6ebd2",
        "inverse-on-surface": "#eff3da",
        "surface-variant": "#e0e5cc",
        "on-tertiary-fixed-variant": "#48473a",
        "inverse-surface": "#2e3222",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdead",
        "on-tertiary-fixed": "#1c1c11",
        "on-primary-fixed-variant": "#274e3d",
        "primary": "#012d1d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.25rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "md": "16px",
        "xs": "4px",
        "xl": "40px",
        "sm": "8px",
        "unit": "4px",
        "lg": "24px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "h1-mobile": ["Literata", "serif"],
        "h1": ["Literata", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "h2": ["Literata", "serif"],
        "label-id": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-sm": ["14px", {"lineHeight": "1.4", "fontWeight": "400"}],
        "button": ["15px", {"lineHeight": "1.0", "fontWeight": "600"}],
        "h1-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-id": ["13px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
};
export default config;
